### ISSUE TITLE
Add  kompose

### ISSUE THREAD

**Issue by jscharber** [pavedroad-io/kevlar-web#9]
@rick4106t,  This is the next step for CI process

@MarkGreenPR, we need the following tools installed for go
docker-compose, https://docs.docker.com/compose/install/
Kubernets Kompose, http://kompose.io/

Next, I will need Skaffold, https://github.com/GoogleContainerTools/skaffold

docker-compose will let me run cockroach and prToken with one command
kompose: will convert the docker compose file into a k8s deployment

I want skaffold so I can deploy containers, add container tests, and add tagging

**Comment by agstaunton** [comment]
changing to just be kompose

**Comment by jscharber** [comment]
@MarkGreenPR  added this, safe to close
